export const Department = () => {
    return (
        <div>
            <h1>Department</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac est est. Duis id elit ante. Curabitur condimentum libero ut hendrerit semper. Duis laoreet, neque at elementum pulvinar, tortor sem cursus ligula, quis sollicitudin tellus lacus ut ligula. Sed sed ligula vestibulum massa egestas bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu pellentesque risus.

                Cras metus tellus, molestie in nisi ut, dignissim sagittis justo. Proin nec lacinia odio. Nulla consequat odio ac magna facilisis tincidunt. In et augue elementum, ullamcorper nulla a, cursus massa. Mauris placerat imperdiet nibh. Donec turpis dolor, pellentesque a augue et, condimentum lacinia nibh. Aenean eleifend porta commodo. Fusce nec est ut ex interdum ullamcorper eu a turpis. Duis porta et lectus et vehicula. Nunc risus felis, fringilla quis lectus at, imperdiet lobortis nibh. Fusce turpis felis, ullamcorper id dolor eget, egestas pharetra dolor. Integer nec ligula sed felis porttitor placerat sit amet ac purus. Integer consequat interdum lectus, vestibulum aliquam dolor congue vel. Suspendisse potenti. Morbi laoreet odio a metus imperdiet blandit.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque malesuada mollis mauris in pretium. Aenean gravida malesuada consequat. Duis tincidunt ultricies ipsum id hendrerit. Vivamus ultricies sem eu purus placerat aliquam. Sed finibus odio et enim commodo vulputate. Donec urna turpis, aliquet vel est ac, pharetra rutrum purus. Sed id cursus mi, ut ornare quam. Curabitur efficitur sem a eros ornare, quis pharetra felis finibus. Maecenas venenatis orci at tortor gravida tempor. Pellentesque fringilla nunc eget enim vulputate, rutrum facilisis magna commodo. Pellentesque pellentesque quam quis mi consectetur, eu lobortis urna blandit.

                Cras finibus nunc leo, sed accumsan metus viverra egestas. Donec id elementum eros. Proin vulputate, est ut pulvinar rhoncus, lacus felis placerat sapien, vitae dignissim tellus arcu sed neque. Sed in odio libero. Ut massa nunc, scelerisque et ligula vitae, bibendum accumsan tortor. Duis nibh velit, eleifend iaculis leo in, rutrum feugiat risus. Aenean dapibus urna ac massa tempus, vitae suscipit felis mattis. Suspendisse ultrices diam tempor, consequat elit ac, mollis diam.

                Etiam eleifend purus eu velit consectetur, at vulputate ex facilisis. Curabitur viverra, velit ac gravida tincidunt, orci quam gravida ex, nec consequat eros nisi sed dui. Donec aliquam purus eget nisi varius, et mattis purus pellentesque. Donec libero lacus, aliquam eget magna eu, pharetra gravida nulla. Suspendisse facilisis ipsum vitae vulputate eleifend. Suspendisse scelerisque placerat augue eget vulputate. Aliquam erat volutpat. Ut vel nisi interdum, pulvinar purus non, ornare dui.
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac est est. Duis id elit ante. Curabitur condimentum libero ut hendrerit semper. Duis laoreet, neque at elementum pulvinar, tortor sem cursus ligula, quis sollicitudin tellus lacus ut ligula. Sed sed ligula vestibulum massa egestas bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu pellentesque risus.

                Cras metus tellus, molestie in nisi ut, dignissim sagittis justo. Proin nec lacinia odio. Nulla consequat odio ac magna facilisis tincidunt. In et augue elementum, ullamcorper nulla a, cursus massa. Mauris placerat imperdiet nibh. Donec turpis dolor, pellentesque a augue et, condimentum lacinia nibh. Aenean eleifend porta commodo. Fusce nec est ut ex interdum ullamcorper eu a turpis. Duis porta et lectus et vehicula. Nunc risus felis, fringilla quis lectus at, imperdiet lobortis nibh. Fusce turpis felis, ullamcorper id dolor eget, egestas pharetra dolor. Integer nec ligula sed felis porttitor placerat sit amet ac purus. Integer consequat interdum lectus, vestibulum aliquam dolor congue vel. Suspendisse potenti. Morbi laoreet odio a metus imperdiet blandit.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque malesuada mollis mauris in pretium. Aenean gravida malesuada consequat. Duis tincidunt ultricies ipsum id hendrerit. Vivamus ultricies sem eu purus placerat aliquam. Sed finibus odio et enim commodo vulputate. Donec urna turpis, aliquet vel est ac, pharetra rutrum purus. Sed id cursus mi, ut ornare quam. Curabitur efficitur sem a eros ornare, quis pharetra felis finibus. Maecenas venenatis orci at tortor gravida tempor. Pellentesque fringilla nunc eget enim vulputate, rutrum facilisis magna commodo. Pellentesque pellentesque quam quis mi consectetur, eu lobortis urna blandit.

                Cras finibus nunc leo, sed accumsan metus viverra egestas. Donec id elementum eros. Proin vulputate, est ut pulvinar rhoncus, lacus felis placerat sapien, vitae dignissim tellus arcu sed neque. Sed in odio libero. Ut massa nunc, scelerisque et ligula vitae, bibendum accumsan tortor. Duis nibh velit, eleifend iaculis leo in, rutrum feugiat risus. Aenean dapibus urna ac massa tempus, vitae suscipit felis mattis. Suspendisse ultrices diam tempor, consequat elit ac, mollis diam.

                Etiam eleifend purus eu velit consectetur, at vulputate ex facilisis. Curabitur viverra, velit ac gravida tincidunt, orci quam gravida ex, nec consequat eros nisi sed dui. Donec aliquam purus eget nisi varius, et mattis purus pellentesque. Donec libero lacus, aliquam eget magna eu, pharetra gravida nulla. Suspendisse facilisis ipsum vitae vulputate eleifend. Suspendisse scelerisque placerat augue eget vulputate. Aliquam erat volutpat. Ut vel nisi interdum, pulvinar purus non, ornare dui.
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac est est. Duis id elit ante. Curabitur condimentum libero ut hendrerit semper. Duis laoreet, neque at elementum pulvinar, tortor sem cursus ligula, quis sollicitudin tellus lacus ut ligula. Sed sed ligula vestibulum massa egestas bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu pellentesque risus.

                Cras metus tellus, molestie in nisi ut, dignissim sagittis justo. Proin nec lacinia odio. Nulla consequat odio ac magna facilisis tincidunt. In et augue elementum, ullamcorper nulla a, cursus massa. Mauris placerat imperdiet nibh. Donec turpis dolor, pellentesque a augue et, condimentum lacinia nibh. Aenean eleifend porta commodo. Fusce nec est ut ex interdum ullamcorper eu a turpis. Duis porta et lectus et vehicula. Nunc risus felis, fringilla quis lectus at, imperdiet lobortis nibh. Fusce turpis felis, ullamcorper id dolor eget, egestas pharetra dolor. Integer nec ligula sed felis porttitor placerat sit amet ac purus. Integer consequat interdum lectus, vestibulum aliquam dolor congue vel. Suspendisse potenti. Morbi laoreet odio a metus imperdiet blandit.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque malesuada mollis mauris in pretium. Aenean gravida malesuada consequat. Duis tincidunt ultricies ipsum id hendrerit. Vivamus ultricies sem eu purus placerat aliquam. Sed finibus odio et enim commodo vulputate. Donec urna turpis, aliquet vel est ac, pharetra rutrum purus. Sed id cursus mi, ut ornare quam. Curabitur efficitur sem a eros ornare, quis pharetra felis finibus. Maecenas venenatis orci at tortor gravida tempor. Pellentesque fringilla nunc eget enim vulputate, rutrum facilisis magna commodo. Pellentesque pellentesque quam quis mi consectetur, eu lobortis urna blandit.

                Cras finibus nunc leo, sed accumsan metus viverra egestas. Donec id elementum eros. Proin vulputate, est ut pulvinar rhoncus, lacus felis placerat sapien, vitae dignissim tellus arcu sed neque. Sed in odio libero. Ut massa nunc, scelerisque et ligula vitae, bibendum accumsan tortor. Duis nibh velit, eleifend iaculis leo in, rutrum feugiat risus. Aenean dapibus urna ac massa tempus, vitae suscipit felis mattis. Suspendisse ultrices diam tempor, consequat elit ac, mollis diam.

                Etiam eleifend purus eu velit consectetur, at vulputate ex facilisis. Curabitur viverra, velit ac gravida tincidunt, orci quam gravida ex, nec consequat eros nisi sed dui. Donec aliquam purus eget nisi varius, et mattis purus pellentesque. Donec libero lacus, aliquam eget magna eu, pharetra gravida nulla. Suspendisse facilisis ipsum vitae vulputate eleifend. Suspendisse scelerisque placerat augue eget vulputate. Aliquam erat volutpat. Ut vel nisi interdum, pulvinar purus non, ornare dui.
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac est est. Duis id elit ante. Curabitur condimentum libero ut hendrerit semper. Duis laoreet, neque at elementum pulvinar, tortor sem cursus ligula, quis sollicitudin tellus lacus ut ligula. Sed sed ligula vestibulum massa egestas bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu pellentesque risus.

                Cras metus tellus, molestie in nisi ut, dignissim sagittis justo. Proin nec lacinia odio. Nulla consequat odio ac magna facilisis tincidunt. In et augue elementum, ullamcorper nulla a, cursus massa. Mauris placerat imperdiet nibh. Donec turpis dolor, pellentesque a augue et, condimentum lacinia nibh. Aenean eleifend porta commodo. Fusce nec est ut ex interdum ullamcorper eu a turpis. Duis porta et lectus et vehicula. Nunc risus felis, fringilla quis lectus at, imperdiet lobortis nibh. Fusce turpis felis, ullamcorper id dolor eget, egestas pharetra dolor. Integer nec ligula sed felis porttitor placerat sit amet ac purus. Integer consequat interdum lectus, vestibulum aliquam dolor congue vel. Suspendisse potenti. Morbi laoreet odio a metus imperdiet blandit.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque malesuada mollis mauris in pretium. Aenean gravida malesuada consequat. Duis tincidunt ultricies ipsum id hendrerit. Vivamus ultricies sem eu purus placerat aliquam. Sed finibus odio et enim commodo vulputate. Donec urna turpis, aliquet vel est ac, pharetra rutrum purus. Sed id cursus mi, ut ornare quam. Curabitur efficitur sem a eros ornare, quis pharetra felis finibus. Maecenas venenatis orci at tortor gravida tempor. Pellentesque fringilla nunc eget enim vulputate, rutrum facilisis magna commodo. Pellentesque pellentesque quam quis mi consectetur, eu lobortis urna blandit.

                Cras finibus nunc leo, sed accumsan metus viverra egestas. Donec id elementum eros. Proin vulputate, est ut pulvinar rhoncus, lacus felis placerat sapien, vitae dignissim tellus arcu sed neque. Sed in odio libero. Ut massa nunc, scelerisque et ligula vitae, bibendum accumsan tortor. Duis nibh velit, eleifend iaculis leo in, rutrum feugiat risus. Aenean dapibus urna ac massa tempus, vitae suscipit felis mattis. Suspendisse ultrices diam tempor, consequat elit ac, mollis diam.

                Etiam eleifend purus eu velit consectetur, at vulputate ex facilisis. Curabitur viverra, velit ac gravida tincidunt, orci quam gravida ex, nec consequat eros nisi sed dui. Donec aliquam purus eget nisi varius, et mattis purus pellentesque. Donec libero lacus, aliquam eget magna eu, pharetra gravida nulla. Suspendisse facilisis ipsum vitae vulputate eleifend. Suspendisse scelerisque placerat augue eget vulputate. Aliquam erat volutpat. Ut vel nisi interdum, pulvinar purus non, ornare dui.
            </p>
        </div>
    )
}
